### ISSUE TITLE
Problems with umlauts and special charcters

### ISSUE THREAD

**Issue by derNicklas** [artarmstrong/FieldtypeRadio#1]
Hey Art! :)

There are two problems with your module:

1. It doesn't save values in the backend with **umlauts** or **special characters**.
   E.g. `München` or `?!?`

2. It doesn't even show the radio in the backend, if you only use **umlauts**.
   E.g. `ÄÖÜ`

Cheers! Nick

**Comment by artarmstrong** [comment]
Sorry for the extrememly late notice. At this point in time this module is deprecated in favor of using the "Page" field type and selecting Radio as the display option.
